version: '2'

volumes:
   prometheus-data:
      driver: rancher-nfs
   consul-data:
      driver: rancher-nfs
   mysql:
      driver: rancher-nfs
   grafana:
      driver: rancher-nfs
services:
  pmm-server:
    image: percona/pmm-server:2
    container_name: pmm-server
    ports:
      - '443:443'
    restart: always
    environment:
      - SERVER_USER=admin
      - SERVER_PASSWORD=admin
      - METRICS_RETENTION=720h
      - METRICS_MEMORY=4194304
      - METRICS_RESOLUTION=1s
      - QUERIES_RETENTION=30
    volumes:
       - prometheus-data:/opt/prometheus/data
       - consul-data:/opt/consul-data
       - mysql:/var/lib/mysql
       - grafana:/var/lib/grafana

    labels:
      io.rancher.container.pull_image: always